# Generated by Django 4.2.3 on 2023-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0003_books_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="discription",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
