# Generated by Django 4.2.3 on 2023-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0005_remove_books_image_bookimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.DeleteModel(
            name="BookImages",
        ),
    ]
