# Generated by Django 4.2.3 on 2023-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0006_books_image_delete_bookimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField()),
                ("minimum_amount", models.IntegerField()),
                ("discount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("is_expired", models.BooleanField(default=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
            ],
        ),
    ]
