# Generated by Django 4.2.3 on 2023-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0007_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
