# Generated by Django 4.2.3 on 2023-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0007_coupon"),
        ("userside", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admins.coupon",
            ),
        ),
    ]
