# Generated by Django 4.2.3 on 2023-10-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0007_coupon"),
        ("userside", "0004_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="books",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="books",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="admins.books",
            ),
            preserve_default=False,
        ),
    ]
