# Generated by Django 4.2.3 on 2023-10-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userside", "0008_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_balance",
            field=models.IntegerField(default=0),
        ),
    ]
