# Generated by Django 4.2.1 on 2023-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
