# Generated by Django 4.2.3 on 2023-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logins", "0002_user_details_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_details",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
