# Generated by Django 4.2.3 on 2023-09-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logins", "0003_alter_user_details_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_details",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user_details",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
